### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ' '

### ISSUE THREAD

**Issue by andrestoga** [TristanBrotherton/netcheck#24]
I'm getting the following error while running the latest commit(81ed016) as of today:

andrestoga@andrestoga-PC-US-HOME:~/netcheck$ ./netcheck.sh 
-----------------------------------------------------------------------------
SpeedTest-CLI:     Installed 
Logging to:        log/connection.log
************ Monitoring started at: Wed 20 Jul 2022 09:58:25 CDT ************
CONNECTED LINK SPEED:                           
Traceback (most recent call last):
  File "/home/andrestoga/netcheck/speedtest-cli.py", line 2000, in <module>
    main()
  File "/home/andrestoga/netcheck/speedtest-cli.py", line 1986, in main
    shell()
  File "/home/andrestoga/netcheck/speedtest-cli.py", line 1875, in shell
    secure=args.secure
  File "/home/andrestoga/netcheck/speedtest-cli.py", line 1091, in __init__
    self.get_config()
  File "/home/andrestoga/netcheck/speedtest-cli.py", line 1174, in get_config
    map(int, server_config['ignoreids'].split(','))
ValueError: invalid literal for int() with base 10: ''
-----------------------------------------------------------------------------

OS: Ubuntu 18.04

**Comment by TristanBrotherton** [comment]
This looks like you're having an issue with the speedtest-cli - please verify you can run it and if needed report the issue there. https://github.com/sivel/speedtest-cli

You can also opt to run netcheck without using the speedtest library.
